[package]
name = "pkm"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
diesel = { version = "2.2.5", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
ratatui = "0.29.0"
